### PR TITLE
Fix bug PE-DRY-RUN issue 197

### LINKED ISSUE #195: [PE-D] Deleted class is still visible in student's profile
Deleted `tn/T04` but `T04` is still displayed in the student profile

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: kaiyichen/ped#14

### LINKED ISSUE #197: [PE-D] Application breaks after attempting to remove a student that does not have an existing tutorial
After typing this,

attempt to add `comment` , `view_comment`, `remove_comment` , `grade` and other commands related to on student with id `e1234567` is not responding

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: kaiyichen/ped#16

### PR DESCRIPTION
**Pull request by zixin448**
FIX #197  FIX #195

### CODE REVIEW

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -388,12 +389,30 @@ public void addStudent(Student student) {
      */
     public void removeStudent(Student student) {
         requireNonNull(student);
+        System.out.println("removing " + student.toString());
```
Comment (honganhcs) [inline src/main/java/seedu/address/model/AddressBook.java:392]: remember to remove print statements hehe!

**Review by honganhcs — APPROVED** [review]
other than print statement, everything looks good!

File: src/main/java/seedu/address/model/AddressBook.java (hunk 1 above)
Comment (zixin448) [reply src/main/java/seedu/address/model/AddressBook.java]: Oops haha updated!! thanks much

**Review by kev-intq — APPROVED** [review]
